# Generated by Django 4.2.2 on 2023-06-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_todoitem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='tags',
            field=models.CharField(default='@', max_length=50),
        ),
    ]
